# Generated by Django 2.2.5 on 2019-10-05 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+6281297126699' or 081297126699. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
