# Generated by Django 2.2.5 on 2019-09-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
