# Generated by Django 2.2.5 on 2020-07-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
